name: Run YouTube Watcher (Confluent Cloud version)

on:
  schedule:
    # Run the workflow every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allows manual triggering of the workflow from the GitHub Actions UI

jobs:
  run-youtube-watcher:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run YouTube Watcher script
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
        KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
        KAFKA_SASL_USERNAME: ${{ secrets.KAFKA_SASL_USERNAME }}
        KAFKA_SASL_PASSWORD: ${{ secrets.KAFKA_SASL_PASSWORD }}
        SCHEMA_REGISTRY_URL: ${{ secrets.SCHEMA_REGISTRY_URL }}
        SCHEMA_REGISTRY_BASIC_AUTH: ${{ secrets.SCHEMA_REGISTRY_BASIC_AUTH }}
      run: |
        python youtube_watcher.py
